const menuItems = {
    "IceSnack": menuIceSnackItems,
    "HotSnack": menuHotSnackItems,
    "Salat": menuSalatItems,
    "MainDisnhes": menuMainDishes,
    "GrillDishes": menuGrillDishes,
    "FirstDishes": menuFirstDishes,
    "Garnier": menuGarnier,
    "Souse": menuSouse,
    "Bread": menuBread,
    "Deserts": menuDesert,
    "Coffee": menuCoffee,
    "Tea": menuTea,
    "IceDrink": menuIceDrink,
    "ZeroCocktail": menuZeroCocktail,
    "Kids": menuKids,
    "AlcoCockt": menuAlcoCockt,
    "FizzyVine": menuFizzyVine,
    "WhiteVine": menuWhiteVine,
    "PinkVine": menuPinkVine,
    "RedVine": menuRedVine,
    "Vermut": menuVermut,
    "Licker": menuLicker,
    "Rome": menuRome,
    "Jin": menuJin,
    "Whiskey": menuWhiskey,
    "Brandi": menuBrandi,
    "Vodka": menuVodka,
    "Tequila": menuTequila,
    "Beer": menuBeer,
    "Hookah": menuHookah,
    "OtherHookah": menuOtherHookah,
    "FruitDop": menuFruitDop,
    "Oter":menuOter
};